// Interactive design study. All AI and voice outputs are local samples.
const extraIcons={koala:'<circle cx="5" cy="8" r="4"/><circle cx="19" cy="8" r="4"/><ellipse cx="12" cy="13" rx="7" ry="8"/><path d="M9 11h.01M15 11h.01"/><ellipse cx="12" cy="14" rx="2" ry="3" fill="currentColor"/>',bunny:'<ellipse cx="8" cy="6" rx="2.5" ry="5"/><ellipse cx="16" cy="6" rx="2.5" ry="5"/><ellipse cx="12" cy="16" rx="8" ry="6"/><path d="M9 15h.01M15 15h.01m-4 3 1 1 1-1"/>',spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3zM20 2v4m-2-2h4"/>',pet:'<ellipse cx="12" cy="16" rx="6" ry="5"/><ellipse cx="4" cy="10" rx="2" ry="3"/><ellipse cx="9" cy="5" rx="2" ry="3"/><ellipse cx="16" cy="5" rx="2" ry="3"/><ellipse cx="21" cy="10" rx="2" ry="3"/>',home:'<path d="m3 10 9-7 9 7v11h-7v-7h-4v7H3z"/>',shop:'<path d="M5 7h14l2 14H3zM8 7V5a4 4 0 0 1 8 0v2"/>',leaf:'<path d="M20 3C7 2 2 8 5 16c8 4 15-2 15-13ZM4 21 16 8"/>',bike:'<circle cx="5" cy="17" r="4"/><circle cx="19" cy="17" r="4"/><path d="m5 17 5-10 5 10H5m5-10 9 10m-3-13h3v4M8 7h4"/>',flag:'<path d="M5 22V3c5-5 9 5 15 0v11c-6 5-10-5-15 0"/>',plus:'<path d="M12 5v14M5 12h14"/>'};for(const [id,paths]of Object.entries(extraIcons))document.querySelector('defs').insertAdjacentHTML('beforeend',`<symbol id="${id}" viewBox="0 0 24 24">${paths}</symbol>`);
const categories={pet:['Lemmikit','pet','peach'],home:['Koti','home','lavender'],shop:['Ostokset','shop','gold'],out:['Asiointi','leaf','mint'],bike:['Pyörä','bike','blue']};
function classify(title){return /eläin|kissa|koira|ruokinta/i.test(title)?'pet':/osta|kauppa|lamppu|maito/i.test(title)?'shop':/pyör|jarru|huolto/i.test(title)?'bike':/kierrä|paperi|puutarha/i.test(title)?'out':'home'}
const seenWorking=new Set();
function person(name,taskId=null){
  const working=taskId!==null,key=taskId+':'+name;
  const animate=working&&!seenWorking.has(key)&&motionAllowed();
  if(working)seenWorking.add(key);
  return `<span class="person ${name==='Jenny'?'jenny':''} ${working?'working':''} ${animate?'motion-working':''}"><span class="worker-avatar">${icon(name==='Jenny'?'bunny':'koala')}${working?'<svg class="work-pencil" aria-hidden="true" viewBox="0 0 24 24"><path d="M3 20h15M7 16l2-5L19 1l4 4-10 10z"/></svg>':''}</span><span>${esc(name)}${working?' tekee':''}</span></span>`;
}

tasks[0].notes='Vuosittainen tarkastus ja rokotukset. Kysy samalla hampaiden kunnosta.';tasks[0].urgent=true;tasks[1].notes='Tehdään tilaa pyörille ennen syksyä.';tasks[3].owner='Jenny';
$('.top').innerHTML=`<div class="topline"><div class="app-brand"><img src="bun-do.svg" alt="Bun Do logo"><strong>Bun Do</strong><span id="view-label"></span></div><button class="avatar" aria-label="Pasi, asetukset" onclick="settings()">${icon('koala')}</button></div>`;
$('.intro h1').innerHTML='A little more<br>done, together.';$('.intro .eyebrow').remove();$('.intro p').textContent='Capture a task, break it into smaller steps, and see what you and Jenny have taken care of.';$('.intro .note').innerHTML='Try “Pilko tekoälyllä” in any task, or dictate the steps yourself. Swipe a row right to finish it.<br><br>AI and recording are simulated. Example data resets on refresh. Profile editing and combo effects are V2 ideas.';
let reorderMode=false, animationsEnabled=true, completionTurn=0;
let editId=null,splitSuggestions=[],recordForSplit=false,splitVoiceText='',period='week',pendingCompletes=new Set();
function render(){let home=view==='tasks';$('#view-label').textContent=home?'':view==='activity'?'Tapahtumat':'Yhdessä';$('#filters').style.display=home?'flex':'none';$('#dock').style.display=home?'flex':'none';$('.nav').innerHTML=[['tasks','Tehtävät','tasks'],['activity','Tapahtumat','clock'],['together','Yhdessä','people']].map(([v,t,i])=>`<button class="${view===v?'active':''}" ${view===v?'aria-current="page"':''} onclick="view='${v}';render()"><span class="nav-icon">${icon(i)}</span>${t}</button>`).join('');$('#filters').innerHTML=[['all','Kaikki'],['free','Vapaana'],['mine','Minulla']].map(([v,t])=>`<button class="chip ${filter===v?'selected':''}" aria-pressed="${filter===v}" onclick="filter='${v}';render()">${t}</button>`).join('');
if(home){let shown=tasks.filter(t=>filter==='all'||(filter==='free'?!t.owner:t.owner==='Pasi'));$('#content').innerHTML=(draft?'<button class="draft-btn" onclick="editDraft(false)">Jatka keskeneräistä tehtävää →</button>':'')+`<div class="list-heading"><span>${shown.length} tehtävää</span><span class="queue-tools"><button class="reorder-toggle" aria-pressed="${reorderMode}" onclick="toggleReorder()">${icon(reorderMode?'check':'order')}${reorderMode?'Valmis':'Järjestä'}</button></span></div>`+`<p class="queue-help">${reorderMode?'Tärkein ylimmäksi. Vedä kahvasta tai käytä nuolia.':'Uudet jonon loppuun. Kiireelliset ja pian erääntyvät alkuun.'}</p>`+shown.map(t=>{let c=categories[classify(t.title)];return `<div class="task ${t.urgent?'urgent':''}" data-row="${t.id}"><button class="check category ${c[2]}" aria-label="${t.list?.length?'Avaa vaiheet':'Merkitse valmiiksi'}: ${esc(t.title)}" onclick="complete(${t.id})">${icon(c[1])}<span class="check-hover">${icon('check')}</span></button><button class="task-main" data-task-id="${t.id}" onclick="detail(${t.id})"><span class="task-copy"><span class="task-title">${esc(t.title)}</span>${t.urgent||t.date?`<span class="meta">${t.urgent?'<span class="urgency">'+icon('flag')+'Kiireellinen</span>':''}${t.date?(t.urgent?' · ':'')+esc(t.date):''}</span>`:''}${t.list?.length?`<span class="mini-progress"><i style="width:${t.list.filter(x=>x[1]).length/t.list.length*100}%"></i></span><span class="meta">${t.list.filter(x=>x[1]).length} / ${t.list.length} vaihetta</span>`:''}${t.owner?person(t.owner,t.id):''}</span>${reorderMode?'':icon('arrow').replace('<svg ','<svg class="chev" ')}</button>${reorderMode?reorderControls(t):''}</div>`}).join('')+(shown.length?'':'<div class="empty"><img src="bun-do.svg" alt=""><p>Lista on tältä osin tyhjä.</p></div>');if(reorderMode)bindReorder();else bindSwipes();$('#filters').hidden=reorderMode;$('#filters').style.display=reorderMode?'none':'flex'}
else if(view==='activity')$('#content').innerHTML='<h2 class="small-heading">Tänään</h2>'+[...events,['Jenny hoiti tehtävän','Kastele kasvit','10.42'],['Pasi hoiti tehtävän','Tilaa kahvia','9.15'],['Jenny lisäsi tehtävän','Osta uusi lamppu','8.50']].map(e=>`<div class="activity">${person(e[0].startsWith('Jenny')?'Jenny':'Pasi')}<div><p>${esc(e[0])}</p><p style="font-weight:600;margin:3px 0">${esc(e[1])}</p><small>${esc(e[2])}</small></div></div>`).join('');else renderStats()}
function renderStats(){let vals=period==='week'?[2,1,3,0,2,4+completed,0]:[8,10,8,12+completed],labels=period==='week'?['Ma','Ti','Ke','To','Pe','La','Su']:['Vko 34','Vko 35','Vko 36','Vko 37'];let total=vals.reduce((a,b)=>a+b,0),max=Math.max(...vals,1);$('#content').innerHTML=`<div class="chart-heading"><h2>Hoidettu yhdessä</h2><div class="period"><button class="${period==='week'?'selected':''}" onclick="period='week';renderStats()">Viikko</button><button class="${period==='month'?'selected':''}" onclick="period='month';renderStats()">Kuukausi</button></div></div><p class="chart-total"><strong>${total}</strong> tehtävää ${period==='week'?'tällä viikolla':'tässä kuussa'}</p><figure class="chart" aria-label="${esc(vals.map((v,i)=>labels[i]+': '+v+' tehtävää').join(', '))}"><div class="bars">${vals.map((v,i)=>`<div class="bar-column"><span>${v}</span><div class="bar-track"><div class="bar" style="height:${v/max*100}%"></div></div><small>${labels[i]}</small></div>`).join('')}</div><figcaption>Yhteiset valmistumiset ${period==='week'?'päivittäin':'viikoittain'}</figcaption></figure><div class="household">${person('Pasi')}${person('Jenny')}</div><section class="streak-panel"><div>${icon('spark')}<h3>4 viikon putki</h3></div><div class="streak-track">${[34,35,36,37].map(n=>`<span>${icon('check')}<small>Vko ${n}</small></span>`).join('')}</div><p>Vähintään yksi tehtävä hoidettu joka viikko.</p></section><section class="milestone"><img src="bun-do.svg" alt=""><div><h3>${126+completed} asiaa hoidettu</h3><p>100 täynnä. Seuraava etappi 250.</p><progress value="${126+completed}" max="250" aria-label="Elinikäiset valmistumiset, seuraava etappi 250"></progress></div></section>`}
function editDraft(fromVoice){if(!draft||fromVoice)editId=null;draft ||= {title:'',notes:'',date:'',list:[],urgent:false};showEditor(fromVoice?'Tarkista tehtävä':'Uusi tehtävä')}
function editTask(id){editId=id;draft=structuredClone(tasks.find(t=>t.id===id));showEditor('Muokkaa tehtävää')}
function showEditor(title='Muokkaa tehtävää'){draft.list ||= [];openSheet(head(title)+`<form id="draft-form"><label for="title">Tehtävä</label><textarea id="title" rows="2" required placeholder="Mitä pitää tehdä?" oninput="draft.title=this.value">${esc(draft.title)}</textarea><label for="notes">Kuvaus</label><textarea id="notes" rows="2" placeholder="Lisätiedot ja muistettavat asiat" oninput="draft.notes=this.value">${esc(draft.notes||'')}</textarea><div class="field-pair"><div><label for="date">Päivä</label><input type="date" id="date" value="${esc(draft.date==='Tänään'?'':draft.date||'')}" oninput="draft.date=this.value;updatePlacementHint()"></div><label class="priority-toggle"><input type="checkbox" ${draft.urgent?'checked':''} onchange="draft.urgent=this.checked;updatePlacementHint()">${icon('flag')}Kiireellinen</label></div><div class="steps-heading"><h3>Vaiheet</h3><span>${draft.list.length}</span></div><div id="steps-editor"></div><button type="button" class="add-step" onclick="addStep()">${icon('plus')}Lisää vaihe</button><div class="ai-actions"><button type="button" onclick="suggestSplit(false)">${icon('spark')}Pilko tekoälyllä</button><button type="button" onclick="recordSteps()">${icon('mic')}Sanele vaiheet</button></div><p class="ai-note">Tarkistat ehdotukset ennen lisäämistä.</p><div class="editor-save"><p id="placement-hint" class="placement-hint" role="status">${placementHint()}</p><button class="primary" type="submit">${editId?'Tallenna muutokset':'Lisää tehtävä'}${icon('check')}</button></div></form><button class="cancel" onclick="draft=null;editId=null;closeSheet()">Hylkää muutokset</button>`);renderSteps();$('#draft-form').onsubmit=e=>{e.preventDefault();save()}}
function renderSteps(){$('#steps-editor').innerHTML=draft.list.map((x,i)=>`<div class="step-edit"><span>${i+1}</span><input aria-label="Vaihe ${i+1}" value="${esc(x[0])}" oninput="draft.list[${i}][0]=this.value"><button type="button" class="icon-btn" aria-label="Poista vaihe ${i+1}" onclick="draft.list.splice(${i},1);renderSteps()">${icon('close')}</button></div>`).join('');$('.steps-heading span').textContent=draft.list.length}
function addStep(){draft.list.push(['',false]);renderSteps();$('#steps-editor').lastElementChild.querySelector('input').focus()}
function suggestions(){let c=classify(draft.title);return c==='bike'?['Valitse huoltoliike','Varaa huoltoaika','Vie pyörä huoltoon']:c==='pet'?['Etsi eläinlääkärin yhteystiedot','Varaa tarkastusaika','Ota rokotuskortti mukaan']:c==='shop'?['Tarkista mitä tarvitaan','Valitse sopiva tuote','Käy ostoksilla']:['Kerää tarvittavat tavarat','Tee ensimmäinen osa','Tarkista lopputulos']}
function suggestSplit(voice){if(!draft.title.trim()){$('#title').focus();return}splitSuggestions=(voice?splitVoiceText.split(/\n|;/).map(x=>x.trim()).filter(Boolean):suggestions()).map(x=>[x,true]);openSheet(head(voice?'Tarkista sanellut vaiheet':'Ehdotus pienemmiksi vaiheiksi')+`<p class="quiet">${esc(draft.title)}</p><p class="ai-note">${voice?'Simuloitu sanelu':'Tekoälyn esimerkkiehdotus'}. Muokkaa tai jätä pois tarpeettomat vaiheet.</p><div>${splitSuggestions.map((x,i)=>`<div class="suggestion"><input type="checkbox" aria-label="Lisää ehdotus ${i+1}" checked onchange="splitSuggestions[${i}][1]=this.checked"><input aria-label="Ehdotus ${i+1}" value="${esc(x[0])}" oninput="splitSuggestions[${i}][0]=this.value"></div>`).join('')}</div><button class="primary" onclick="acceptSplit()">Lisää valitut vaiheet</button><button class="cancel" onclick="showEditor()">Takaisin muokkaamaan</button>`)}
function acceptSplit(){let existing=new Set(draft.list.map(x=>x[0].toLowerCase()));for(const [s,on]of splitSuggestions)if(on&&s.trim()&&!existing.has(s.trim().toLowerCase())){draft.list.push([s.trim(),false]);existing.add(s.trim().toLowerCase())}showEditor()}
function recordSteps(){if(!draft.title.trim()){$('#title').focus();return}recordForSplit=true;splitVoiceText='Kerää tarvittavat tavarat\nTee ensimmäinen osa\nTarkista lopputulos';openSheet(head('Sanele tehtävän vaiheet')+`<p class="quiet">Kerro, miten haluat jakaa tehtävän.</p><p class="ai-note">Simuloitu äänitys. Voit muuttaa esimerkkisanelua alla.</p><label for="spoken-steps">Sanellut vaiheet, yksi per rivi</label><textarea id="spoken-steps" oninput="splitVoiceText=this.value">${esc(splitVoiceText)}</textarea><button class="primary" onclick="suggestSplit(true)">${icon('stop')}Lopeta ja tarkista</button><button class="cancel" onclick="showEditor()">Peruuta sanelu</button>`)}
function record(){if(draft){editDraft(false);return}seconds=0;openSheet(head('Sano tehtävä ääneen')+`<div class="record"><p class="sample">Esimerkkitallennus · mikrofonia ei käytetä</p><div class="timer" id="timer">0:00</div><div class="wave" aria-hidden="true">${Array.from({length:23},(_,i)=>`<i style="--h:${16+Math.sin(i*2.3)**2*45}px;--d:${i*-.12}s"></i>`).join('')}</div><p>Voit kertoa myös kuvauksen ja vaiheet.</p></div><label for="capture-sample">Kokeile sanelua</label><select id="capture-sample"><option value="simple">Pyörän huolto</option><option value="steps">Varaston järjestely vaiheineen</option></select><button class="primary" onclick="stopRecording()">${icon('stop')}Lopeta</button><button class="cancel" onclick="closeSheet()">Peruuta</button>`);timer=setInterval(()=>{seconds++;if($('#timer'))$('#timer').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')},1000)}
function stopRecording(){clearInterval(timer);let steps=$('#capture-sample').value==='steps';draft=steps?{title:'Järjestä varasto',notes:'Tehdään tilaa pyörille.',list:[['Lajittele työkalut',false],['Vie pahvit keräykseen',false],['Lahjoita ylimääräiset',false]],date:'',urgent:false}:{title:'Varaa aika pyörän huoltoon',notes:'Takajarru vinkuu.',list:[],date:'',urgent:false};editDraft(true)}
function save(){if(!draft.title.trim()){$('#title').focus();return}let old=editId?tasks.find(t=>t.id===editId):null,previous=old?structuredClone(old):null;let t={...draft,id:editId||Date.now(),createdBy:old?.createdBy||'Pasi',createdAt:old?.createdAt||new Date().toISOString(),modifiedBy:'Pasi',modifiedAt:new Date().toISOString(),title:draft.title.trim(),list:draft.list.filter(x=>x[0].trim()).map(x=>[x[0].trim(),x[1]])};if(old)tasks[tasks.indexOf(old)]=t;else tasks.splice(initialPosition(t),0,t);const addedMessage=expedited(t)?'Lisätty kiireellisten joukkoon':'Lisätty jonon loppuun';draft=null;editId=null;filter='all';view='tasks';reorderMode=false;closeSheet();document.querySelector(`[data-row="${t.id}"]`)?.scrollIntoView({block:'nearest'});notify(old?'Muutokset tallennettu':addedMessage,()=>{if(previous)tasks[tasks.indexOf(t)]=previous;else tasks=tasks.filter(x=>x!==t);render()},old?null:'file')}
function detail(id){let t=tasks.find(t=>t.id===id);openSheet(head('Tehtävä')+`<h3 class="detail-title">${esc(t.title)}</h3>${t.urgent?'<span class="urgency">'+icon('flag')+'Kiireellinen</span>':''}${taskHistory(t)}<h4>Kuvaus</h4><p class="description">${t.notes?esc(t.notes):'Ei kuvausta vielä.'}</p>${t.date?'<p class="quiet">'+esc(t.date)+'</p>':''}<div class="steps-heading"><h3>Vaiheet</h3><button onclick="editTask(${id});addStep()">${icon('plus')}Lisää</button></div>${t.list?.length?'<ul class="detail-list">'+t.list.map((x,i)=>`<li><label><input type="checkbox" ${x[1]?'checked':''} onchange="toggleItem(${id},${i},this.checked)"><span>${esc(x[0])}</span></label></li>`).join('')+'</ul>':'<p class="quiet">Jaa tehtävä pienempiin vaiheisiin.</p>'}<div class="ai-actions"><button onclick="editTask(${id});suggestSplit(false)">${icon('spark')}Pilko tekoälyllä</button><button onclick="editTask(${id});recordSteps()">${icon('mic')}Sanele vaiheet</button></div><p>${t.owner?person(t.owner,t.id):'Vapaana meille kummallekin.'}</p><div class="sheet-footer"><button ${t.owner==='Jenny'||t.list?.length?'disabled':''} onclick="claim(${id})">${t.list?.length?'Ota yksittäinen vaihe':t.owner==='Pasi'?'Vapauta tehtävä':t.owner?'Jenny tekee tämän':'Otan tämän'}</button><button onclick="editTask(${id})">Muokkaa</button></div><button class="primary" ${t.list?.length?'disabled':''} onclick="complete(${id})">${icon('check')}${t.list?.length?'Valmistuu vaiheista':'Merkitse valmiiksi'}</button>`)}
function claim(id){let t=tasks.find(t=>t.id===id);if(t.owner==='Jenny')return;seenWorking.delete(id+':Pasi');t.owner=t.owner?null:'Pasi';touchTask(t);detail(id);render();if(t.owner){if(motionAllowed())$('#sheet .person')?.classList.add('claim-stamp');notify('Otit tehtävän itsellesi',null,'claim')}else notify('Tehtävä on taas vapaana')}
function settings(){openSheet(head('Meidän koti')+`<div class="profile-pair">${person('Pasi')}${person('Jenny')}</div><div class="sheet-footer"><button onclick="toggleTheme()">Vaihda vaalea / tumma</button></div><label class="motion-setting"><input type="checkbox" ${animationsEnabled?'checked':''} onchange="animationsEnabled=this.checked">Pienet toimintoanimaatiot</label><p class="ai-note">Valmistumisessa vuorottelevat kumarrus, pieni loikka ja valmis-leima. Laitteen vähennetty liike ohittaa valinnan.</p><p class="quiet">Profiilikuvien muokkaus on V2-idea.</p><p class="ai-note">Interaktiivinen luonnos. Tekoäly ja äänitys ovat simuloituja. Muutokset nollautuvat sivun päivityksessä.</p>`)}
function complete(id){
  const i=tasks.findIndex(x=>x.id===id), t=tasks[i];
  if(!t)return;
  if(t.list?.length){detail(id);notify('Merkitse vaiheet valmiiksi yksi kerrallaan');return}
  const previous=structuredClone(t);const row=document.querySelector(`[data-row="${id}"]`);const rowRect=row?.getBoundingClientRect();const closingRow=row?.cloneNode(true);
  touchTask(t);
  tasks.splice(i,1);completed++;
  const e=['Pasi hoiti tehtävän',t.title,auditTime(new Date().toISOString())];events.unshift(e);
  if(!$('#overlay').hidden)closeSheet();else render();
  const effect=['bow','hop','stamp'][completionTurn++%3];
  if(closingRow&&rowRect&&motionAllowed()){const bounds=$('#app').getBoundingClientRect();closingRow.removeAttribute('data-row');closingRow.querySelectorAll('[data-task-id]').forEach(el=>el.removeAttribute('data-task-id'));closingRow.classList.add('closing-task','close-'+effect);closingRow.setAttribute('aria-hidden','true');closingRow.inert=true;Object.assign(closingRow.style,{left:(rowRect.left-bounds.left)+'px',top:(rowRect.top-bounds.top)+'px',width:rowRect.width+'px',height:rowRect.height+'px'});$('#app').append(closingRow);setTimeout(()=>closingRow.remove(),420)}
  notify('Hyvä! Yksi asia vähemmän.',()=>{tasks.splice(Math.min(i,tasks.length),0,previous);completed--;events=events.filter(x=>x!==e);render()},effect);
}
function bindSwipes(){document.querySelectorAll('[data-row]').forEach(row=>{let start=null,swiped=false;row.style.touchAction='pan-y';row.addEventListener('pointerdown',e=>{if(e.button!==0)return;start={x:e.clientX,y:e.clientY};swiped=false});row.addEventListener('pointerup',e=>{if(start&&e.clientX-start.x>90&&Math.abs(e.clientY-start.y)<45){swiped=true;complete(Number(row.dataset.row))}start=null});row.addEventListener('pointercancel',()=>start=null);row.addEventListener('click',e=>{if(swiped){e.preventDefault();e.stopPropagation();swiped=false}},true)})}

