/* Throwaway native-flow study. Three structures share sample data, never production APIs. */
const icons={back:'M19 12H5m6-6-6 6 6 6',next:'m9 6 6 6-6 6',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',task:'M9 6h11M9 12h11M9 18h11M3 6h1M3 12h1M3 18h1',calendar:'M5 4h14v16H5zM5 9h14M8 2v4M16 2v4',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',mic:'M9 5a3 3 0 0 1 6 0v6a3 3 0 0 1-6 0zM5 10v1a7 7 0 0 0 14 0v-1M12 18v4M8 22h8',heart:'M12 20 3 11C-2 4 8 0 12 7c4-7 14-3 9 4z',edit:'m4 16-1 5 5-1L20 7l-4-4zM14 5l4 4',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.task}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));
const specs={A:{name:'Everything together',text:'One scrolling editor. Title, steps and schedule are all visible, with one Save. Fast for familiar tasks; longer when the task gets complicated.'},B:{name:'A short guided edit',text:'Task → Steps → When. Each phase has one job. Move freely between phases and save at any point. More guidance, more taps.'},C:{name:'Edit where you read',text:'Edit opens the task in place. Every section shows its value and an Edit control. Expand only what you need, then save once. Less jumping; hidden fields need clear summaries.'}};
let variant=new URLSearchParams(location.search).get('variant')||'A';if(!specs[variant])variant='A';
const initial=[{id:1,title:'Get the balcony ready for autumn',description:'Bring the delicate plants inside and make room for the colder weather.',steps:[{text:'Bring the basil inside',done:true},{text:'Sweep the balcony',done:false},{text:'Cover the outdoor chairs',done:false}],due:'2026-09-20',time:'',urgent:false,snooze:'',repeat:'none',weekday:'Sunday',repeatTitle:'Get the balcony ready for autumn',claim:false,status:'active',audience:'Our home',original:'balcony before it gets cold, bring basil in, sweep and cover chairs'},{id:2,title:'Wash the bed linen',description:'Use the gentle cycle for the linen sheets.',steps:[],due:'',time:'',urgent:false,snooze:'',repeat:'weekly',weekday:'Saturday',repeatTitle:'Wash the bed linen',claim:false,status:'active',audience:'Our home',original:'Wash the bed linen'},{id:3,title:'Book a haircut',description:'',steps:[],due:'',time:'',urgent:false,snooze:'',repeat:'none',weekday:'Sunday',repeatTitle:'Book a haircut',claim:false,status:'active',audience:'Only me',original:'Book a haircut'}];
let tasks=clone(initial),selected=1,screen='detail',draft=null,step=0,section='task',isNew=false,offline=false,filter='active',audience='Our home',recording=false,toastTimer,aiReturn='editor',activity=[],settingsReturn='queue';
const $=s=>document.querySelector(s),task=()=>tasks.find(t=>t.id===selected),button=(label,action,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const ib=(name,action,label)=>button(icon(name),action,'icon-button',`aria-label="${label}"`);
function notify(message,undo){clearTimeout(toastTimer);$('#toast').innerHTML=esc(message)+(undo?button('Undo','undo'):'');$('#toast').classList.add('show');window.undoAction=undo;toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),6500)}
function header(title,back='home',sub=''){return `<header class="app-header">${back?ib('back',back,'Back'): '<img src="assets/bun.svg" alt="">'}<h2>${esc(title)}${sub?`<small>${esc(sub)}</small>`:''}</h2>${!back?ib('settings','settings','Settings'):''}</header>`}
const footer=(html,hint='')=>`<footer class="footer">${hint?`<p class="hint">${hint}</p>`:''}<div class="row">${html}</div></footer>`;
const field=(name,label,value,type='text',hint='')=>`<label class="field">${label}${type==='textarea'?`<textarea data-field="${name}">${esc(value)}</textarea>`:`<input type="${type}" data-field="${name}" value="${esc(value)}">`}${hint?`<span class="hint">${hint}</span>`:''}</label>`;
function choose(name,label,value,values,hint=''){return `<label class="field">${label}<select data-field="${name}">${values.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${l}</option>`).join('')}</select>${hint?`<span class="hint">${hint}</span>`:''}</label>`}
function nav(){return `<nav class="nav" aria-label="Main navigation">${[['task','Tasks','queue'],['check','Lists','lists'],['heart','Together','together'],['calendar','Activity','activity']].map(([i,l,s])=>button(icon(i)+l,s,screen===s?'active':'')).join('')}</nav>`}
function taskForm(){return `${field('title','Task title',draft.title)}${field('description','Description',draft.description,'textarea')}<div class="options">${button('Tidy wording with AI','tidy')}${button(icon('mic')+' Add a spoken revision','revision')}</div><p class="hint">AI suggestions are shown for review before anything changes.</p>${isNew?choose('audience','Who can see this?',draft.audience,[['Our home','Our home'],['Only me','Only me']],'Only me tasks are private. Claiming a shared task does not make it private.'): `<p class="hint">Visible to ${esc(draft.audience.toLowerCase())}. ${draft.audience==='Only me'?'Sharing is a separate action, never a side effect of Save.':''}</p>`}`}
function stepsForm(){return `<p class="hint">Edit the checklist here. Completed steps keep their status.</p>${draft.steps.map((s,i)=>`<div class="check-row"><span class="hint">${i+1}.</span><input type="text" aria-label="Step ${i+1}" data-step="${i}" value="${esc(s.text)}">${ib('close','remove-step:'+i,'Remove step '+(i+1))}</div>`).join('')}${button(icon('plus')+' Add a step','add-step','secondary')} ${button('Suggest steps with AI','suggest','quiet')}<p class="hint">These are direct steps, not nested tasks.</p>`}
function whenForm(){return `<div class="row">${field('due','Due date',draft.due,'date')}${field('time','Time, optional',draft.time,'time')}</div><div class="options">${button('Tomorrow','tomorrow')}${button('No due date','clear-date')}</div><label class="toggle-line"><input type="checkbox" data-field="urgent" ${draft.urgent?'checked':''}>Urgent</label><h3 style="margin-top:24px">Hide until later</h3>${choose('snooze','Snooze',draft.snooze,[['','Do not hide'],['hour','For one hour'],['tomorrow','Until tomorrow morning'],['week','For one week']],'Snooze hides this task for a while. It does not change the due date.')}<h3>Future repeats</h3>${choose('repeat','Repeat plan',draft.repeat,[['none','Does not repeat'],['daily','Daily'],['weekly','Weekly']])}${draft.repeat==='weekly'?choose('weekday','Repeat on',draft.weekday,['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(x=>[x,x])):''}${draft.repeat!=='none'?field('repeatTitle','Title for future copies',draft.repeatTitle,'text','This task keeps its own title. Repeat settings apply to future copies only.'):''}<p class="hint">Repeat changes require a connection. Dates and ordinary task edits work offline. Times use Europe/Helsinki.</p>${offline&&repeatChanged()?'<div class="notice">Your repeat plan cannot be saved offline. Save task only keeps the repeat draft open for later.</div>':''}`}
function repeatChanged(){const old=isNew?{repeat:'none',weekday:'Sunday',repeatTitle:''}:task();return ['repeat','weekday','repeatTitle'].some(k=>draft[k]!==old[k])&&!(draft.repeat==='none'&&old.repeat==='none')}
function sections(){return [['task','Task',taskForm],['steps','Steps',stepsForm],['when','When',whenForm]]}
function editor(){let body='';const seq=sections();if(variant==='A')body=`<div class="content">${seq.map(([k,n,f])=>`<section class="section"><h3>${n==='Task'?'The task':n==='When'?'Dates and repeats':'Checklist'} </h3>${f()}</section>`).join('')}</div>`;
if(variant==='B')body=`<div class="content"><h3>${['What needs doing?','Make it manageable','When does it matter?'][step]}</h3>${seq[step][2]()}</div>`;
if(variant==='C')body=`<div class="content"><h2 class="detail-title">${esc(draft.title||'New task')}</h2><p class="read-first-note">Edit any section. Save applies your task changes together.</p>${seq.map(([k,n,f])=>`<section class="section"><div class="section-heading"><h3>${n}</h3>${button(section===k?'Collapse':'Edit','section:'+k,'',`aria-expanded="${section===k}"`)}</div>${section===k?f():`<p class="hint">${k==='task'?esc(draft.description||'No description'):k==='steps'?`${draft.steps.length} checklist steps`:esc([draft.due||'No due date',draft.snooze?'Snoozed':'Not snoozed',draft.repeat==='none'?'No repeat':draft.repeat+' repeat'].join(' · '))}</p>`}</section>`).join('')}</div>`;
return header(isNew?'New task':'Edit task','leave-editor',isNew?'Not saved yet':'Changes stay in this draft')+(variant==='B'?`<nav class="tab-strip" aria-label="Edit phases">${seq.map(([k,n],i)=>button(`${i+1}. ${n}`,'phase:'+i,i===step?'selected':'',`aria-current="${i===step?'step':'false'}"`)).join('')}</nav>`:'')+`<div class="scroll">${body}</div>`+footer((variant==='B'&&step<2?button('Next: '+seq[step+1][1],'next','secondary'):button('Cancel','leave-editor','secondary'))+button(offline&&repeatChanged()?'Save task only':isNew?'Create task':'Save changes','save','primary',!draft.title.trim()?'disabled':''),!draft.title.trim()?'Enter a task title to save.':variant==='B'?'You can save now. Later phases are optional.':'No task changes are applied until you save.')}
function detail(){const t=task();return header('Task','home',t.audience)+`<div class="scroll"><div class="scene" aria-hidden="true"></div><div class="detail-content"><h1 class="detail-title">${esc(t.title)}</h1><div class="meta">${[t.status==='done'?'Completed':t.status==='deleted'?'Deleted':t.claim?'Claimed by you':'Unclaimed',t.due?'Due '+t.due:'',t.urgent?'Urgent':'',t.repeat!=='none'?t.repeat+' repeat':'',t.snooze?'Snoozed':''].filter(Boolean).map(v=>`<span class="tag">${esc(v)}</span>`).join('')}</div><p>${esc(t.description)}</p>${t.steps.length?`<section class="section"><div class="section-heading"><h3>Checklist</h3><span class="hint">${t.steps.filter(s=>s.done).length} / ${t.steps.length}</span></div>${t.steps.map((s,i)=>`<div class="check-row"><input id="step-${i}" type="checkbox" data-complete-step="${i}" ${s.done?'checked':''} ${t.snooze?'disabled':''}><label for="step-${i}" class="${s.done?'done':''}">${esc(s.text)}</label></div>`).join('')}${button('Edit steps','edit-steps','quiet')}</section>`:''}<section class="section">${button(`<span><strong>Dates and repeats</strong><small>${esc(t.due||'No due date')} · ${t.repeat==='none'?'Does not repeat':esc(t.repeat)}</small></span>${icon('next')}`,'edit-when','summary-row')}${t.audience!=='Only me'?button(t.claim?'Release this task':'I&#39;ll do this','claim','quiet'):''}${button('Original text and history','original','summary-row')}</section>${t.status!=='deleted'?button(icon('trash')+' Delete task','delete','quiet danger'):''}</div></div>`+footer(button('Edit task','edit','secondary',t.status==='deleted'?'disabled':'')+button(t.status==='deleted'?'Restore task':t.status==='done'?'Reopen task':t.steps.length?'Complete remaining steps':'Mark complete',t.status==='deleted'?'restore':'complete','primary',t.snooze?'disabled':''),t.snooze?'Snoozed tasks cannot be completed. Remove snooze in Edit.':'')}
function queue(){let list=tasks.filter(t=>t.audience===audience&&(filter==='mine'?t.status==='active'&&t.claim:filter==='snoozed'?t.status==='active'&&t.snooze:t.status===filter));if(filter==='active')list=list.filter(t=>!t.snooze);return header('Bun Do','')+`<div class="scroll"><div class="scene" style="height:130px" aria-hidden="true"></div><div class="content"><div class="row">${choose('audience-filter','Task space',audience,[['Our home','Our home'],['Only me','Only me']])}${choose('filter','Show',filter,[['active','Active'],['mine','Claimed by me'],['snoozed','Snoozed'],['done','Completed'],['deleted','Deleted']])}</div><p class="hint">${list.length} ${list.length===1?'task':'tasks'}</p>${list.length?list.map(t=>`<div class="task-row"><span class="cue">${icon(t.steps.length?'task':'calendar')}</span>${button(esc(t.title)+`<small>${esc(t.status==='done'?'Completed':t.claim?'Claimed by you':t.due?'Due '+t.due:'No due date')}</small>`,'open:'+t.id,'task-title')}${ib('next','open:'+t.id,'Open '+esc(t.title))}</div>`).join(''):`<div class="empty"><h3>No ${filter==='mine'?'claimed':filter} tasks here.</h3><p class="hint">${filter==='active'?'Capture something when you need to.':'Your other tasks are still in Active.'}</p>${button('Show active tasks','active','secondary')}</div>`}${button('Our home adventure','adventure','summary-row')}</div></div>`+footer(button(icon('plus')+' Write','new','secondary')+button(icon('mic')+' Speak a task','voice','primary'))+nav()}
function lists(){return header('Lists','', 'Our home · Reusable checklists')+`<div class="scroll content"><h2>Start with a familiar list</h2><p class="hint">Using a list creates a task. Editing that task does not change the reusable list.</p>${button(`<span><strong>Weekend reset</strong><small>3 steps · Reusable list</small></span>${icon('next')}`,'list-preview','summary-row')}${button(`<span><strong>Pack for a day out</strong><small>4 steps · Reusable list</small></span>${icon('next')}`,'list-preview','summary-row')}</div>`+nav()}
function simplePage(title,content){return header(title,'home',audience)+`<div class="scroll content">${content}</div>`+nav()}
function voice(){return header('Speak a task','home',audience)+`<div class="scroll content"><div class="recording">${icon('mic')}<h2>${recording?'Sample recording':'Voice capture'}</h2><p>No microphone is used in this demo.</p><strong>${recording?'00:06':'00:00'}</strong><p class="hint">Sample: “Get the balcony ready. Bring in the basil, sweep, and cover the chairs.”</p></div></div>`+footer(button('Type instead','new','secondary')+button(recording?'Stop and review':'Start sample','voice-next','primary'))}
function review(){return header('Review task','leave-editor','Voice draft · Not saved')+`<div class="scroll"><div class="scene" aria-hidden="true"></div><div class="detail-content"><h1 class="detail-title">${esc(draft.title)}</h1><p>${esc(draft.description)}</p><h3>Checklist</h3>${draft.steps.map((s,i)=>`<p>${i+1}. ${esc(s.text)}</p>`).join('')}<p class="hint">Sample transcript is kept with this draft. Saving creates a task.</p>${button('Edit all details','edit-review','secondary')}${button('Revise with a sample instruction','revision','summary-row')}</div></div>`+footer(button('Keep draft','keep-draft','secondary')+button('Create task','save','primary'))}
function aiPage(){const proposed=window.proposed;return header('Review suggestion','keep-current','Sample AI output · Not saved')+`<div class="scroll content"><p>Only accept the changes you want. Your current draft is still here.</p><div class="review-old"><h3>Current</h3><p>${esc(draft.title)}</p><p>${esc(draft.description)}</p>${draft.steps.map(s=>`<p>${esc(s.text)}</p>`).join('')}</div><div class="review-new"><h3>Proposed</h3><p>${esc(proposed.title)}</p><p>${esc(proposed.description)}</p>${proposed.steps.map(s=>`<p>${esc(s.text)}</p>`).join('')}</div></div>`+footer(button('Keep current','keep-current','secondary')+button('Use suggestion','accept-ai','primary'),'Using a suggestion changes the draft. It does not save a task.')}
function render(){let html;if(screen==='detail')html=detail();else if(screen==='editor')html=editor();else if(screen==='queue')html=queue();else if(screen==='voice')html=voice();else if(screen==='review')html=review();else if(screen==='ai')html=aiPage();else if(screen==='lists')html=lists();else if(screen==='original')html=header('Original text and history','detail')+`<div class="scroll content"><h3>Captured text</h3><p>${esc(task().original)}</p><h3>Task activity</h3><p class="hint">Sample task created by you. Original text does not change when you edit the task.</p></div>`;else if(screen==='settings')html=header('Settings',settingsReturn)+`<div class="scroll content">${button('<span><strong>Household and account</strong><small>Our home · Sample household</small></span>'+icon('next'),'account','summary-row')}${button('<span><strong>Voice and recordings</strong><small>Automatic speech · Audio not kept</small></span>'+icon('next'),'voice-settings','summary-row')}${button('<span><strong>Reminders</strong><small>About due tasks, not snooze</small></span>'+icon('next'),'reminders','summary-row')}<h3 style="margin-top:28px">Study controls</h3><label class="toggle-line"><input type="checkbox" id="offline" ${offline?'checked':''}>Simulate offline</label><p class="hint">The study uses English sample copy. Finnish native layouts still need separate validation.</p></div>`;
else if(screen==='voice-settings')html=simplePage('Voice and recordings',`<p>Speech recognition and AI editing are separate choices.</p><h3>Speech recognition</h3><p class="hint">Automatic. Use online speech when connected, installed local speech otherwise.</p><h3>AI suggestions</h3><p class="hint">Optional transcript analysis. Review suggestions before saving.</p><h3>Saved recordings</h3><p class="hint">Off. Audio is not retained after transcription.</p>${button('Try a sample capture','voice','primary')}`);
else if(screen==='reminders')html=simplePage('Reminders','<h3>Due tasks</h3><p>Reminders use task due dates. Snooze only hides a task from the active queue.</p><p class="hint">Android permission controls are outside this browser study.</p>');
else if(screen==='account')html=simplePage('Household and account','<h3>Our home</h3><p>You and Alex share tasks here.</p><h3>Private tasks</h3><p>Choose Only me in Tasks for private work. “Claimed by me” still means a shared household task.</p><p class="hint">Sign-in, invitations, export and account deletion are not connected in this study.</p>');
else if(screen==='together')html=simplePage('Together',`<h2>Our home this week</h2><p>Sample shared progress. This is not a member ranking.</p>${button('Continue the household adventure','adventure','summary-row')}`);
else if(screen==='activity')html=simplePage('Activity',activity.length?activity.map(a=>`<p>${esc(a)}</p>`).join(''):'<p>No actions in this sample session yet. Edit or complete a task to see it here.</p>');
else if(screen==='adventure')html=simplePage('Our home adventure',`<h2>Make room for autumn</h2><p>Three household steps. The balcony task is one of them.</p>${button('Open balcony task','open:1','summary-row')}<p class="hint">Adventure generation is outside this editing study. It would use the same task editor, not another set of editing menus.</p>`);
$('#phone').innerHTML=html;if(screen==='queue'&&draft){const write=document.querySelector('[data-action="new"]');if(write){write.dataset.action='resume';write.textContent='Resume draft';}}$('#variant-description').innerHTML=`<section class="study-description"><h2>${variant}. ${specs[variant].name}</h2><p>${specs[variant].text}</p></section>`;$('#switcher').innerHTML=ib('back','previous-variant','Previous variant')+`<span>${variant} · ${specs[variant].name}</span>`+ib('next','next-variant','Next variant');$('#state').textContent=JSON.stringify({variant,screen,offline,draft,tasks},null,2)}
function beginEdit(newTask=false){if(draft){screen='editor';selected=draft.id;notify('Resumed your unfinished draft. Save or discard it before starting another.');render();return false}isNew=newTask;draft=newTask?{...clone(initial[1]),id:Date.now(),title:'',description:'',steps:[],due:'',repeat:'none',repeatTitle:'',audience,original:''}:clone(task());step=0;section=variant==='C'?'':'task';screen='editor';render();return true}
function confirm(title,text,actions){const d=$('#confirm');d.innerHTML=`<h2>${title}</h2><p>${text}</p><div class="row">${actions.map(([l,a,c])=>button(l,a,c)).join('')}</div>`;d.showModal()}
function save(){if(!draft.title.trim())return;selected=draft.id;const repeatPending=offline&&repeatChanged();let saved=clone(draft);saved.title=saved.title.trim();saved.steps=saved.steps.filter(s=>s.text.trim());if(saved.steps.length)saved.status=saved.steps.every(s=>s.done)?'done':'active';if(repeatPending){const old=isNew?{repeat:'none',weekday:'Sunday',repeatTitle:saved.title}:task();for(const k of ['repeat','weekday','repeatTitle'])saved[k]=old[k]}
if(isNew){saved.original=saved.original||saved.title;tasks.push(saved);selected=saved.id}else tasks=tasks.map(t=>t.id===selected?saved:t);activity.unshift('You '+(isNew?'created':'edited')+' '+saved.title);isNew=false;if(repeatPending){screen='editor';notify('Task saved. The repeat plan is still an unsaved draft.')}else{draft=null;screen='detail';notify('Task saved in this demo.')}render()}
function switchVariant(delta){variant=['A','B','C'][(['A','B','C'].indexOf(variant)+delta+3)%3];const u=new URL(location);u.searchParams.set('variant',variant);history.replaceState({},'',u);render();console.info('Prototype state', {variant,screen,draft,tasks})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const [a,v]=b.dataset.action.split(':');if(a==='previous-variant'||a==='next-variant'){switchVariant(a==='next-variant'?1:-1);return}if(a==='reset'){tasks=clone(initial);draft=null;selected=1;screen='detail';activity=[];render();return}if(a==='undo'){window.undoAction?.();$('#toast').classList.remove('show');return}if(a==='open'){selected=Number(v);screen='detail'}else if(a==='home'){screen='queue'}else if(['queue','lists','together','activity','adventure','account','voice-settings','reminders','original','detail'].includes(a)){if(['lists','together','activity','adventure'].includes(a)&&audience==='Only me'){audience='Our home';notify('Switched to Our home. Private tasks stay private.')}screen=a}
else if(a==='settings'){settingsReturn=screen;screen='settings'}else if(a==='edit'||a==='new'){beginEdit(a==='new');return}else if(a==='edit-steps'||a==='edit-when'){beginEdit();step=a==='edit-steps'?1:2;section=a==='edit-steps'?'steps':'when';render();if(variant==='A')setTimeout(()=>$('#phone .scroll').scrollTop=a==='edit-steps'?410:850,0);return}
else if(a==='phase'){step=Number(v)}else if(a==='next'){step=Math.min(2,step+1)}else if(a==='section'){section=section===v?'':v}else if(a==='add-step'){draft.steps.push({text:'',done:false})}else if(a==='remove-step'){draft.steps.splice(Number(v),1)}else if(a==='tomorrow'){draft.due='2026-09-20'}else if(a==='clear-date'){draft.due='';draft.time=''}else if(a==='save'){save();return}else if(a==='leave-editor'){confirm('Leave this draft?','No changes have been applied to the task. Keep the draft to come back to it, or discard your changes.',[['Keep editing','dismiss','secondary'],['Keep draft','keep-draft','primary'],['Discard','discard','danger']]);return}else if(a==='dismiss'){$('#confirm').close();return}else if(a==='keep-draft'){$('#confirm').close();screen='queue';notify('Draft kept for this demo session. Use Resume draft.')}else if(a==='discard'){$('#confirm').close();draft=null;screen=isNew?'queue':'detail';isNew=false}else if(a==='resume'){selected=draft.id;screen='editor'}else if(a==='claim'){task().claim=!task().claim;notify(task().claim?'You claimed this task. It is still shared.':'Task released.')}
else if(a==='complete'){if(task().status==='done'){task().status='active';task().steps.forEach(s=>s.done=false);notify('Task reopened.')}else if(task().steps.length){confirm('Complete all remaining steps?','This checklist finishes when all its steps are complete.',[['Keep working','dismiss','secondary'],['Complete steps','confirm-complete','primary']]);return}else{const completedId=task().id;task().status='done';activity.unshift('You completed '+task().title);notify('Task completed.',()=>{const completed=tasks.find(t=>t.id===completedId);if(completed?.status==='done')completed.status='active';render()})}}
else if(a==='confirm-complete'){$('#confirm').close();const old=clone(task());task().steps.forEach(s=>s.done=true);task().status='done';activity.unshift('You completed '+task().title);notify('Checklist completed.',()=>{tasks=tasks.map(t=>t.id===old.id?old:t);render()})}
else if(a==='delete'){confirm('Delete this task?','You can restore it from Deleted tasks. Deleting stops its repeat plan; restoring does not restart it. Reusable lists are unchanged.',[['Keep task','dismiss','secondary'],['Delete task','confirm-delete','danger']]);return}else if(a==='confirm-delete'){$('#confirm').close();const t=task(),old=t.status;t.status='deleted';t.repeat='none';screen='queue';notify('Task deleted.',()=>{t.status=old;render()})}else if(a==='restore'){task().status='active';notify('Task restored.')}else if(a==='active'){filter='active'}
else if(a==='voice'){if(draft){screen='editor';selected=draft.id;notify('Resumed your unfinished draft. Save or discard it before recording.')}else{recording=false;screen='voice'}}else if(a==='voice-next'){if(!recording)recording=true;else{draft=clone(initial[0]);draft.id=Date.now();draft.due='';draft.steps.forEach(s=>s.done=false);isNew=true;screen='review'}}else if(a==='edit-review'){screen='editor';step=0;section='task'}else if(a==='list-preview'){if(!beginEdit(true))return;draft.title='Weekend reset';draft.steps=[{text:'Change the towels',done:false},{text:'Wipe the kitchen surfaces',done:false},{text:'Take out the recycling',done:false}];draft.original='Reusable list: Weekend reset';notify('New task from a reusable list. The template stays unchanged.');render();return}
else if(['tidy','suggest','revision'].includes(a)){if(offline){notify('Sample AI is unavailable offline. You can still edit manually.');return}aiReturn=screen;window.proposed=clone(draft);if(a==='tidy'){window.proposed.title='Prepare the balcony for autumn';window.proposed.description='Bring plants indoors, sweep the floor and cover the chairs.'}else if(a==='suggest'){window.proposed.steps=draft.steps.length?[...clone(draft.steps),{text:'Put the cleaning supplies away',done:false}]:[{text:'Gather what you need',done:false},{text:'Finish the main task',done:false},{text:'Put everything away',done:false}]}else{window.proposed.steps.push({text:'Check the plant saucers for water',done:false})}screen='ai'}else if(a==='keep-current'){screen=aiReturn}else if(a==='accept-ai'){draft=clone(window.proposed);screen=aiReturn;notify('Suggestion accepted into the draft. Not saved yet.')}
render();});
document.addEventListener('input',e=>{if(e.target.dataset.step!==undefined)draft.steps[Number(e.target.dataset.step)].text=e.target.value;const k=e.target.dataset.field;if(!k||!draft)return;if(['audience-filter','filter'].includes(k))return;draft[k]=e.target.type==='checkbox'?e.target.checked:e.target.value;const saveButton=$('[data-action="save"]');if(saveButton){saveButton.disabled=!draft.title.trim();const hint=document.querySelector('.footer .hint');if(hint)hint.textContent=draft.title.trim()?'No task changes are applied until you save.':'Enter a task title to save.';}$('#state').textContent=JSON.stringify({variant,screen,offline,draft,tasks},null,2)});
document.addEventListener('change',e=>{const k=e.target.dataset.field;if(k==='audience-filter'){audience=e.target.value;render()}else if(k==='filter'){filter=e.target.value;render()}else if(k==='repeat'){if(draft.repeat!=='none'&&!draft.repeatTitle.trim())draft.repeatTitle=draft.title;const scroll=$('#phone .scroll').scrollTop;render();$('#phone .scroll').scrollTop=scroll}else if(e.target.id==='offline'){offline=e.target.checked;render()}else if(e.target.dataset.completeStep!==undefined){const t=task();t.steps[Number(e.target.dataset.completeStep)].done=e.target.checked;t.status=t.steps.every(s=>s.done)?'done':'active';render()}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable||$('#confirm').open)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();switchVariant(e.key==='ArrowRight'?1:-1)}});
if(new URLSearchParams(location.search).get('screen')==='editor')beginEdit();else render();
